// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: areas.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProductsByArea = `-- name: CountProductsByArea :one
SELECT COUNT(*) FROM products WHERE area_id = $1
`

func (q *Queries) CountProductsByArea(ctx context.Context, areaID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProductsByArea, areaID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createArea = `-- name: CreateArea :one
INSERT INTO areas (name, description)
VALUES ($1, $2)
RETURNING id, name, description, created_at
`

type CreateAreaParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateArea(ctx context.Context, arg CreateAreaParams) (Area, error) {
	row := q.db.QueryRow(ctx, createArea, arg.Name, arg.Description)
	var i Area
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const deleteArea = `-- name: DeleteArea :exec
DELETE FROM areas WHERE id = $1
`

func (q *Queries) DeleteArea(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteArea, id)
	return err
}

const findAreaByID = `-- name: FindAreaByID :one
SELECT id, name, description, created_at FROM areas WHERE id = $1
`

func (q *Queries) FindAreaByID(ctx context.Context, id pgtype.UUID) (Area, error) {
	row := q.db.QueryRow(ctx, findAreaByID, id)
	var i Area
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const findAreaByName = `-- name: FindAreaByName :one
SELECT id, name, description, created_at FROM areas WHERE name = $1
`

func (q *Queries) FindAreaByName(ctx context.Context, name string) (Area, error) {
	row := q.db.QueryRow(ctx, findAreaByName, name)
	var i Area
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listAreas = `-- name: ListAreas :many
SELECT id, name, description, created_at FROM areas ORDER BY name ASC
`

func (q *Queries) ListAreas(ctx context.Context) ([]Area, error) {
	rows, err := q.db.Query(ctx, listAreas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Area
	for rows.Next() {
		var i Area
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArea = `-- name: UpdateArea :one
UPDATE areas
SET
    name = COALESCE($1, name),
    description = COALESCE($2, description)
WHERE id = $3
RETURNING id, name, description, created_at
`

type UpdateAreaParams struct {
	Name        pgtype.Text `json:"name"`
	Description pgtype.Text `json:"description"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateArea(ctx context.Context, arg UpdateAreaParams) (Area, error) {
	row := q.db.QueryRow(ctx, updateArea, arg.Name, arg.Description, arg.ID)
	var i Area
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}
