// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Area struct {
	ID          pgtype.UUID      `json:"id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type Product struct {
	ID               pgtype.UUID      `json:"id"`
	Code             string           `json:"code"`
	Url              string           `json:"url"`
	AreaID           pgtype.UUID      `json:"area_id"`
	Description      pgtype.Text      `json:"description"`
	ManufacturerCode pgtype.Text      `json:"manufacturer_code"`
	Quantity         pgtype.Int4      `json:"quantity"`
	ReplacementUrl   pgtype.Text      `json:"replacement_url"`
	SapCode          pgtype.Text      `json:"sap_code"`
	Observations     pgtype.Text      `json:"observations"`
	MinQuantity      pgtype.Int4      `json:"min_quantity"`
	MaxQuantity      pgtype.Int4      `json:"max_quantity"`
	InventoryStatus  pgtype.Text      `json:"inventory_status"`
	LifecycleStatus  pgtype.Text      `json:"lifecycle_status"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
}

type ProductSnapshot struct {
	ID          pgtype.UUID      `json:"id"`
	ProductID   pgtype.UUID      `json:"product_id"`
	Description string           `json:"description"`
	Status      pgtype.Text      `json:"status"`
	RawHtml     pgtype.Text      `json:"raw_html"`
	CollectedAt pgtype.Timestamp `json:"collected_at"`
}

type User struct {
	ID        pgtype.UUID      `json:"id"`
	Name      string           `json:"name"`
	Email     string           `json:"email"`
	Password  string           `json:"password"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
