// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: product_snapshots.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProductSnapshots = `-- name: CountProductSnapshots :one
SELECT COUNT(*) FROM product_snapshots WHERE product_id = $1
`

func (q *Queries) CountProductSnapshots(ctx context.Context, productID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProductSnapshots, productID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSnapshot = `-- name: CreateSnapshot :one
INSERT INTO product_snapshots (product_id, description, status, raw_html)
VALUES ($1, $2, $3, $4)
RETURNING id, product_id, description, status, raw_html, collected_at
`

type CreateSnapshotParams struct {
	ProductID   pgtype.UUID `json:"product_id"`
	Description string      `json:"description"`
	Status      pgtype.Text `json:"status"`
	RawHtml     pgtype.Text `json:"raw_html"`
}

func (q *Queries) CreateSnapshot(ctx context.Context, arg CreateSnapshotParams) (ProductSnapshot, error) {
	row := q.db.QueryRow(ctx, createSnapshot,
		arg.ProductID,
		arg.Description,
		arg.Status,
		arg.RawHtml,
	)
	var i ProductSnapshot
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Description,
		&i.Status,
		&i.RawHtml,
		&i.CollectedAt,
	)
	return i, err
}

const deleteOldSnapshots = `-- name: DeleteOldSnapshots :exec
DELETE FROM product_snapshots
WHERE product_id = $1
AND collected_at < $2
`

type DeleteOldSnapshotsParams struct {
	ProductID   pgtype.UUID      `json:"product_id"`
	CollectedAt pgtype.Timestamp `json:"collected_at"`
}

func (q *Queries) DeleteOldSnapshots(ctx context.Context, arg DeleteOldSnapshotsParams) error {
	_, err := q.db.Exec(ctx, deleteOldSnapshots, arg.ProductID, arg.CollectedAt)
	return err
}

const findSnapshotByID = `-- name: FindSnapshotByID :one
SELECT id, product_id, description, status, raw_html, collected_at FROM product_snapshots WHERE id = $1
`

func (q *Queries) FindSnapshotByID(ctx context.Context, id pgtype.UUID) (ProductSnapshot, error) {
	row := q.db.QueryRow(ctx, findSnapshotByID, id)
	var i ProductSnapshot
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Description,
		&i.Status,
		&i.RawHtml,
		&i.CollectedAt,
	)
	return i, err
}

const getLatestSnapshot = `-- name: GetLatestSnapshot :one
SELECT id, product_id, description, status, raw_html, collected_at FROM product_snapshots
WHERE product_id = $1
ORDER BY collected_at DESC
LIMIT 1
`

func (q *Queries) GetLatestSnapshot(ctx context.Context, productID pgtype.UUID) (ProductSnapshot, error) {
	row := q.db.QueryRow(ctx, getLatestSnapshot, productID)
	var i ProductSnapshot
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Description,
		&i.Status,
		&i.RawHtml,
		&i.CollectedAt,
	)
	return i, err
}

const getSnapshotStatusHistory = `-- name: GetSnapshotStatusHistory :many
SELECT id, status, collected_at
FROM product_snapshots
WHERE product_id = $1
ORDER BY collected_at ASC
`

type GetSnapshotStatusHistoryRow struct {
	ID          pgtype.UUID      `json:"id"`
	Status      pgtype.Text      `json:"status"`
	CollectedAt pgtype.Timestamp `json:"collected_at"`
}

func (q *Queries) GetSnapshotStatusHistory(ctx context.Context, productID pgtype.UUID) ([]GetSnapshotStatusHistoryRow, error) {
	rows, err := q.db.Query(ctx, getSnapshotStatusHistory, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSnapshotStatusHistoryRow
	for rows.Next() {
		var i GetSnapshotStatusHistoryRow
		if err := rows.Scan(&i.ID, &i.Status, &i.CollectedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductSnapshots = `-- name: ListProductSnapshots :many
SELECT id, product_id, description, status, raw_html, collected_at FROM product_snapshots
WHERE product_id = $1
ORDER BY collected_at DESC
`

func (q *Queries) ListProductSnapshots(ctx context.Context, productID pgtype.UUID) ([]ProductSnapshot, error) {
	rows, err := q.db.Query(ctx, listProductSnapshots, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductSnapshot
	for rows.Next() {
		var i ProductSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Description,
			&i.Status,
			&i.RawHtml,
			&i.CollectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotsByDateRange = `-- name: ListSnapshotsByDateRange :many
SELECT id, product_id, description, status, raw_html, collected_at FROM product_snapshots
WHERE product_id = $1
AND collected_at BETWEEN $2 AND $3
ORDER BY collected_at DESC
`

type ListSnapshotsByDateRangeParams struct {
	ProductID     pgtype.UUID      `json:"product_id"`
	CollectedAt   pgtype.Timestamp `json:"collected_at"`
	CollectedAt_2 pgtype.Timestamp `json:"collected_at_2"`
}

func (q *Queries) ListSnapshotsByDateRange(ctx context.Context, arg ListSnapshotsByDateRangeParams) ([]ProductSnapshot, error) {
	rows, err := q.db.Query(ctx, listSnapshotsByDateRange, arg.ProductID, arg.CollectedAt, arg.CollectedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductSnapshot
	for rows.Next() {
		var i ProductSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Description,
			&i.Status,
			&i.RawHtml,
			&i.CollectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
