// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountProductSnapshots(ctx context.Context, productID pgtype.UUID) (int64, error)
	CountProducts(ctx context.Context) (int64, error)
	CountProductsByArea(ctx context.Context, areaID pgtype.UUID) (int64, error)
	CountProductsByAreaAndSearch(ctx context.Context, arg CountProductsByAreaAndSearchParams) (int64, error)
	CountProductsByLifecycleStatus(ctx context.Context) (CountProductsByLifecycleStatusRow, error)
	CountProductsBySearch(ctx context.Context, search string) (int64, error)
	CountProductsInArea(ctx context.Context, areaID pgtype.UUID) (int64, error)
	CountUniqueProducts(ctx context.Context) (int64, error)
	CountUniqueProductsByAreaAndSearch(ctx context.Context, arg CountUniqueProductsByAreaAndSearchParams) (int64, error)
	CountUniqueProductsBySearch(ctx context.Context, search string) (int64, error)
	CountUniqueProductsInArea(ctx context.Context, areaID pgtype.UUID) (int64, error)
	CreateArea(ctx context.Context, arg CreateAreaParams) (Area, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateSnapshot(ctx context.Context, arg CreateSnapshotParams) (ProductSnapshot, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteArea(ctx context.Context, id pgtype.UUID) error
	DeleteOldSnapshots(ctx context.Context, arg DeleteOldSnapshotsParams) error
	DeleteProduct(ctx context.Context, id pgtype.UUID) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	FindAreaByID(ctx context.Context, id pgtype.UUID) (Area, error)
	FindAreaByName(ctx context.Context, name string) (Area, error)
	FindByEmail(ctx context.Context, email string) (User, error)
	FindByID(ctx context.Context, id pgtype.UUID) (User, error)
	FindProductByCode(ctx context.Context, code string) (FindProductByCodeRow, error)
	FindProductByCodeAndArea(ctx context.Context, arg FindProductByCodeAndAreaParams) (FindProductByCodeAndAreaRow, error)
	FindProductByID(ctx context.Context, id pgtype.UUID) (FindProductByIDRow, error)
	FindSnapshotByID(ctx context.Context, id pgtype.UUID) (ProductSnapshot, error)
	GetLatestSnapshot(ctx context.Context, productID pgtype.UUID) (ProductSnapshot, error)
	GetSnapshotStatusHistory(ctx context.Context, productID pgtype.UUID) ([]GetSnapshotStatusHistoryRow, error)
	ListAllProductsToCollect(ctx context.Context) ([]ListAllProductsToCollectRow, error)
	ListAreas(ctx context.Context) ([]Area, error)
	ListProductSnapshots(ctx context.Context, productID pgtype.UUID) ([]ProductSnapshot, error)
	ListProducts(ctx context.Context) ([]ListProductsRow, error)
	ListProductsByArea(ctx context.Context, areaID pgtype.UUID) ([]ListProductsByAreaRow, error)
	ListProductsByAreaPaginated(ctx context.Context, arg ListProductsByAreaPaginatedParams) ([]ListProductsByAreaPaginatedRow, error)
	ListProductsPaginated(ctx context.Context, arg ListProductsPaginatedParams) ([]ListProductsPaginatedRow, error)
	ListSnapshotsByDateRange(ctx context.Context, arg ListSnapshotsByDateRangeParams) ([]ProductSnapshot, error)
	ListUniqueProductCodesToCollect(ctx context.Context) ([]ListUniqueProductCodesToCollectRow, error)
	ListUniqueProductsByAreaPaginated(ctx context.Context, arg ListUniqueProductsByAreaPaginatedParams) ([]ListUniqueProductsByAreaPaginatedRow, error)
	ListUniqueProductsPaginated(ctx context.Context, arg ListUniqueProductsPaginatedParams) ([]ListUniqueProductsPaginatedRow, error)
	ListUsers(ctx context.Context) ([]User, error)
	SearchProducts(ctx context.Context, arg SearchProductsParams) ([]SearchProductsRow, error)
	SearchProductsByArea(ctx context.Context, arg SearchProductsByAreaParams) ([]SearchProductsByAreaRow, error)
	SearchUniqueProductsByAreaPaginated(ctx context.Context, arg SearchUniqueProductsByAreaPaginatedParams) ([]SearchUniqueProductsByAreaPaginatedRow, error)
	SearchUniqueProductsPaginated(ctx context.Context, arg SearchUniqueProductsPaginatedParams) ([]SearchUniqueProductsPaginatedRow, error)
	UpdateArea(ctx context.Context, arg UpdateAreaParams) (Area, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateProductLifecycleStatus(ctx context.Context, arg UpdateProductLifecycleStatusParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
